apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-fastapi-app
  labels:
    app: sample-fastapi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-fastapi-app
  template:
    metadata:
      labels:
        app: sample-fastapi-app
    spec:
      containers:
      - name: sample-fastapi-app
        image: aravindnys/sample-fastapi-app:06842f72
        ports:
          - containerPort: 8000
        resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"