apiVersion: v1
kind: Service
metadata:
  name: sample-fastapi-app
  labels:
    app: sample-fastapi-app
spec:
  type: LoadBalancer
  selector:
    app: sample-fastapi-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000